version: '2.1'

services:
  cert-sync:
    image: admirito/gvmd:11
    volumes:
      - openvas-var-lib:/var/lib/openvas
      - gvm-var-lib:/var/lib/gvm
      - run-redis:/var/run/redis
      - run-ospd:/var/run/ospd
    command: greenbone-certdata-sync --curl --verbose

    depends_on:
      gvmd:
        condition: service_started
