apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gvm.fullname" . }}-gvmd
  labels:
  {{- $_ := set . "applicationNameSuffix" "gvmd" }}
  {{- include "gvm.labels" . | nindent 4 }}
  {{- $_ := set . "applicationNameSuffix" "" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gvm.name" . }}-gvmd
      app.kubernetes.io/instance: {{ include "gvm.instance" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gvm.name" . }}-gvmd
        app.kubernetes.io/instance: {{ include "gvm.instance" . }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ tpl .Values.image.gvmd.registry . }}/{{ tpl .Values.image.gvmd.repository . }}:{{ tpl .Values.image.gvmd.tag . }}"
          imagePullPolicy: {{ tpl .Values.image.gvmd.pullPolicy . }}
          env:
            - name: GVMD_POSTGRESQL_HOST
              value: {{ .Release.Name }}-gvmd-db
            - name: GVMD_POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "gvmd.secretName" . }}
                  key: postgresql-password
            - name: GVMD_POSTGRESQL_URI
              value: "postgresql://gvmduser:$(GVMD_POSTGRESQL_PASSWORD)@$(GVMD_POSTGRESQL_HOST):5432/gvmd?application_name=gvmd"
          ports:
            - name: gvmd
              containerPort: 9390
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: gvmd
          readinessProbe:
            tcpSocket:
              port: gvmd
          volumeMounts:
            - name: run-dir
              mountPath: /var/run
            - name: ospd-socket-dir
              mountPath: /var/run/ospd
            - name: data-volume
              subPath: {{ include "gvm.dataSubPathPrefix" . }}plugins
              mountPath: /var/lib/openvas/plugins
            - name: data-volume
              subPath: {{ include "gvm.dataSubPathPrefix" . }}cert-data
              mountPath: /var/lib/gvm/cert-data
            - name: data-volume
              subPath: {{ include "gvm.dataSubPathPrefix" . }}scap-data
              mountPath: /var/lib/gvm/scap-data
          resources:
            {{- toYaml .Values.resources.gvmd | nindent 12 }}
        - name: {{ .Chart.Name }}-openvas-connector
          image: "{{ tpl .Values.image.socat.registry . }}/{{ tpl .Values.image.socat.repository . }}:{{ tpl .Values.image.socat.tag . }}"
          imagePullPolicy: {{ tpl .Values.image.socat.pullPolicy . }}
          args: ["-d", "-d", "UNIX-LISTEN:/var/run/ospd/ospd.sock,fork", "TCP4-CONNECT:{{ include "gvm.fullname" . }}-openvas:9391"]
          volumeMounts:
            - name: run-dir
              mountPath: /var/run
            - name: ospd-socket-dir
              mountPath: /var/run/ospd
          resources:
            {{- toYaml .Values.resources.gvmdOpenvasConnector | nindent 12 }}
      volumes:
        - name: run-dir
          emptyDir: {}
        - name: ospd-socket-dir
          emptyDir: {}
        - name: data-volume
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ tpl .Values.persistence.existingClaim . | default (include "gvm.fullname" .) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
